package com.github.mouse0w0.instantcoffee;

public enum TokenType {
    END_OF_FILE,
    KEYWORD,
    OPERATOR,
    IDENTIFIER,
    NULL_LITERAL,
    BOOLEAN_LITERAL,
    CHARACTER_LITERAL,
    INTEGER_LITERAL,
    FLOATING_POINT_LITERAL,
    STRING_LITERAL,
    WHITE_SPACE,
    SINGLE_LINE_COMMENT,
    MULTI_LINE_COMMENT
}
